services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n_app
    environment:
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - GENERIC_TIMEZONE=${TIMEZONE}
      - TZ=${TIMEZONE}
      - WEBHOOK_URL=https://n8n.${DOMAIN}/
      - EXECUTIONS_DATA_PRUNE=true
      - EXECUTIONS_DATA_MAX_AGE=168
      - EXECUTIONS_DATA_PRUNE_MAX_COUNT=1000
    volumes:
      - ${STORAGE_PATH}/n8n:/home/node/.n8n
    networks:
      - caddy_net
    restart: unless-stopped

networks:
  caddy_net:
    external: true