import logging
import sqlite3
from typing import Any
from app.config import settings

logger = logging.getLogger("database")

def get_connection() -> sqlite3.Connection:
    conn = sqlite3.connect(settings.db_path)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA foreign_keys = ON")
    return conn

def init_db() -> None:
    settings.data_dir.mkdir(parents=True, exist_ok=True)
    with get_connection() as conn:
        cursor = conn.cursor()
        
        # Track processed financial documents to prevent duplicate extraction
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS processed_documents (
                document_id INTEGER PRIMARY KEY,
                title TEXT,
                created_date TEXT,
                modified_date TEXT,
                doc_type TEXT,
                correspondent TEXT,
                processed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                status TEXT DEFAULT 'completed'
            )
        """)

        # Tabular structured transactions extracted from statements and receipts
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS transactions (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                document_id INTEGER NOT NULL,
                date TEXT,
                description TEXT NOT NULL,
                amount REAL NOT NULL,
                type TEXT DEFAULT 'gasto',
                category TEXT DEFAULT 'General',
                currency TEXT DEFAULT 'MXN',
                account_name TEXT,
                FOREIGN KEY(document_id) REFERENCES processed_documents(document_id) ON DELETE CASCADE
            )
        """)

        cursor.execute("CREATE INDEX IF NOT EXISTS idx_trans_date ON transactions(date)")
        cursor.execute("CREATE INDEX IF NOT EXISTS idx_trans_category ON transactions(category)")
        cursor.execute("CREATE INDEX IF NOT EXISTS idx_trans_doc ON transactions(document_id)")

        # Sync state metadata
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS sync_state (
                key TEXT PRIMARY KEY,
                value TEXT,
                updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        """)

        conn.commit()
    logger.info(f"Database initialized at {settings.db_path}")

def is_document_processed(document_id: int, modified_date: str) -> bool:
    with get_connection() as conn:
        cursor = conn.cursor()
        cursor.execute(
            "SELECT modified_date FROM processed_documents WHERE document_id = ?",
            (document_id,),
        )
        row = cursor.fetchone()
        if not row:
            return False
        # If modified date matches, it has already been processed without changes
        return row["modified_date"] == modified_date

def record_document_and_transactions(
    document_id: int,
    title: str,
    created_date: str,
    modified_date: str,
    doc_type: str,
    correspondent: str,
    transactions: list[dict[str, Any]],
) -> None:
    with get_connection() as conn:
        cursor = conn.cursor()
        # Remove previous transactions if document was re-indexed
        cursor.execute("DELETE FROM transactions WHERE document_id = ?", (document_id,))
        
        cursor.execute(
            """
            INSERT OR REPLACE INTO processed_documents 
            (document_id, title, created_date, modified_date, doc_type, correspondent, processed_at, status)
            VALUES (?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, 'completed')
            """,
            (document_id, title, created_date, modified_date, doc_type, correspondent),
        )

        for t in transactions:
            cursor.execute(
                """
                INSERT INTO transactions 
                (document_id, date, description, amount, type, category, currency, account_name)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?)
                """,
                (
                    document_id,
                    t.get("date"),
                    t.get("description", "Sin descripción"),
                    float(t.get("amount", 0.0)),
                    t.get("type", "gasto"),
                    t.get("category", "General"),
                    t.get("currency", "MXN"),
                    t.get("account_name", correspondent or ""),
                ),
            )
        conn.commit()

def execute_read_only_query(sql_query: str) -> list[dict[str, Any]]:
    """Execute safe read-only SQL queries generated by the LLM."""
    clean_sql = sql_query.strip().rstrip(";")
    upper_sql = clean_sql.upper()

    # Strict safety guard: only SELECT allowed
    if not upper_sql.startswith("SELECT") and not upper_sql.startswith("WITH"):
        raise ValueError("Only SELECT queries are allowed for security.")

    forbidden = ["INSERT", "UPDATE", "DELETE", "DROP", "ALTER", "CREATE", "ATTACH", "DETACH", "PRAGMA", "REPLACE"]
    for keyword in forbidden:
        # Check if forbidden word is present as a standalone token
        words = upper_sql.split()
        if keyword in words:
            raise ValueError(f"Disallowed SQL keyword: {keyword}")

    with get_connection() as conn:
        cursor = conn.cursor()
        cursor.execute(clean_sql)
        rows = cursor.fetchall()
        return [dict(row) for row in rows]

def get_stats() -> dict[str, Any]:
    with get_connection() as conn:
        cursor = conn.cursor()
        cursor.execute("SELECT COUNT(*) as doc_count FROM processed_documents")
        doc_count = cursor.fetchone()["doc_count"]

        cursor.execute("SELECT COUNT(*) as trans_count, SUM(amount) as total_amount FROM transactions")
        t_row = cursor.fetchone()

        cursor.execute("SELECT MIN(date) as min_date, MAX(date) as max_date FROM transactions")
        d_row = cursor.fetchone()

        return {
            "processed_documents": doc_count,
            "total_transactions": t_row["trans_count"] or 0,
            "total_volume": round(t_row["total_amount"] or 0.0, 2),
            "date_range": {
                "min": d_row["min_date"],
                "max": d_row["max_date"],
            }
        }
